const currencyFlags = {
  BGN: 'https://restcountries.eu/data/bgr.svg',
  NOK: 'https://restcountries.eu/data/nor.svg',
  USD: 'https://restcountries.eu/data/asm.svg',
  BRL: 'https://restcountries.eu/data/bra.svg',
  GBP: 'https://restcountries.eu/data/imn.svg',
  RUB: 'https://restcountries.eu/data/rus.svg',
  RON: 'https://restcountries.eu/data/rou.svg',
  NZD: 'https://restcountries.eu/data/cok.svg',
  JPY: 'https://restcountries.eu/data/jpn.svg',
  DKK: 'https://restcountries.eu/data/dnk.svg',
  HRK: 'https://restcountries.eu/data/hrv.svg',
  HUF: 'https://restcountries.eu/data/hun.svg',
  HKD: 'https://restcountries.eu/data/hkg.svg',
  AUD: 'https://restcountries.eu/data/aus.svg',
  ILS: 'https://restcountries.eu/data/isr.svg',
  PHP: 'https://restcountries.eu/data/phl.svg',
  PLN: 'https://restcountries.eu/data/pol.svg',
  ZAR: 'https://restcountries.eu/data/zaf.svg',
  MYR: 'https://restcountries.eu/data/mys.svg',
  MXN: 'https://restcountries.eu/data/mex.svg',
  CHF: 'https://restcountries.eu/data/lie.svg',
  CNY: 'https://restcountries.eu/data/chn.svg',
  CAD: 'https://restcountries.eu/data/can.svg',
  CZK: 'https://restcountries.eu/data/cze.svg',
  KRW: 'https://restcountries.eu/data/kor.svg',
  SGD: 'https://restcountries.eu/data/sgp.svg',
  SEK: 'https://restcountries.eu/data/swe.svg',
  TRY: 'https://restcountries.eu/data/tur.svg',
  THB: 'https://restcountries.eu/data/tha.svg',
  INR: 'https://restcountries.eu/data/ind.svg',
  IDR: 'https://restcountries.eu/data/idn.svg',
};

export default currencyFlags;
